name: Trigger auto deployment for pwaapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pwaapi-AutoDeployTrigger-10d6a3eb-36b4-42aa-9ddb-bbe05ad0ad23.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PWAAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PWAAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PWAAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: acrdvfvluycp45lo.azurecr.io
          registryUsername: ${{ secrets.PWAAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PWAAPI_REGISTRY_PASSWORD }}
          containerAppName: pwaapi
          resourceGroup: rg-adjutum
          imageToBuild: acrdvfvluycp45lo.azurecr.io/pwaapi:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


